server:
  port: 8787

spring:
  application:
    name: spring-security-demo
  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?serverTimezone=GMT%2B8
    username: root
    password: root

